/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesSlugIndexRouteImport } from './routes/services.$slug.index'
import { Route as ServicesSlugProjectRouteImport } from './routes/services.$slug.$project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugIndexRoute = ServicesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesSlugRoute,
} as any)
const ServicesSlugProjectRoute = ServicesSlugProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => ServicesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/services/$slug/$project': typeof ServicesSlugProjectRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/$slug/$project': typeof ServicesSlugProjectRoute
  '/services/$slug': typeof ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/services/$slug/$project': typeof ServicesSlugProjectRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/services/$slug' | '/services/$slug/$project' | '/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/services/$slug/$project' | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/services/$slug'
    | '/services/$slug/$project'
    | '/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesSlugRoute: typeof ServicesSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug/': {
      id: '/services/$slug/'
      path: '/'
      fullPath: '/services/$slug/'
      preLoaderRoute: typeof ServicesSlugIndexRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
    '/services/$slug/$project': {
      id: '/services/$slug/$project'
      path: '/$project'
      fullPath: '/services/$slug/$project'
      preLoaderRoute: typeof ServicesSlugProjectRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
  }
}

interface ServicesSlugRouteChildren {
  ServicesSlugProjectRoute: typeof ServicesSlugProjectRoute
  ServicesSlugIndexRoute: typeof ServicesSlugIndexRoute
}

const ServicesSlugRouteChildren: ServicesSlugRouteChildren = {
  ServicesSlugProjectRoute: ServicesSlugProjectRoute,
  ServicesSlugIndexRoute: ServicesSlugIndexRoute,
}

const ServicesSlugRouteWithChildren = ServicesSlugRoute._addFileChildren(
  ServicesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesSlugRoute: ServicesSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
